apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: sample-app
spec:
  selector:
    app: sample-app
  ports:
  - port: 80
    name: http
  # Using an IP from the default restricted CIDR pool (192.168.0.224/28)
  loadBalancerIP: 192.168.0.225
  allocateLoadBalancerNodePorts: false
  # allocateLoadBalancerNodePorts: true
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: nginx
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
