apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-2
  labels:
    app: echo-server-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server-2
  template:
    metadata:
      labels:
        app: echo-server-2
    spec:
      containers:
      - name: echo-server
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello from echo server 2!"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-2
  labels:
    app: echo-server-2
spec:
  ports:
  - port: 8080
    targetPort: 5678
    protocol: TCP
    name: http
  selector:
    app: echo-server-2
  type: LoadBalancer
